import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Shared/Navbar/Navbar'
import Footer from '@/components/Shared/Footer/page'
import MobNav from '@/components/Shared/Navbar/MobNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <Navbar/>
      <MobNav/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
